/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as adapterSol from "./adapter.sol";
export type { adapterSol };
import type * as feedSol from "./feed.sol";
export type { feedSol };
import type * as helpers from "./helpers";
export type { helpers };
import type * as interface from "./interface";
export type { interface };
import type * as ngnSol from "./ngn.sol";
export type { ngnSol };
import type * as vaultSol from "./vault.sol";
export type { vaultSol };
