/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iAdapterSol from "./IAdapter.sol";
export { IFeed__factory } from "./IFeed__factory";
export { IMedian__factory } from "./IMedian__factory";
export { IVault__factory } from "./IVault__factory";
export { IxNGN__factory } from "./IxNGN__factory";
