[profile.default]
solc = "0.8.21"
src = "src"
test = "test"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./deployConfigs/localnet.json" }, { access = "read", path = "./deployConfigs/testnet.base.json" }]
bytecode_hash = "none"
cbor_metadata = false
evm_version = "paris"
optimizer = true
optimizer_runs = 1_000_000


[rpc_endpoints]
base_georli = "${BASE_TESTNET_RPC_URL}"


[fuzz]
runs = 10000
max_test_rejects = 0
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true


[invariant]
runs = 1000
depth = 50
fail_on_revert = true
dictionary_weight = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
