/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INGNXAdapter__factory } from "./INGNXAdapter__factory";
export { IUSDCAdapter__factory } from "./IUSDCAdapter__factory";
