/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INGNXAdapter,
  INGNXAdapterInterface,
} from "../../../../contracts/interface/IAdapter.sol/INGNXAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_vaultId",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_vaultId",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INGNXAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): INGNXAdapterInterface {
    return new Interface(_abi) as INGNXAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INGNXAdapter {
    return new Contract(address, _abi, runner) as unknown as INGNXAdapter;
  }
}
