/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUSDCAdapter,
  IUSDCAdapterInterface,
} from "../../../../contracts/interface/IAdapter.sol/IUSDCAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_vaultId",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_vaultId",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUSDCAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IUSDCAdapterInterface {
    return new Interface(_abi) as IUSDCAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUSDCAdapter {
    return new Contract(address, _abi, runner) as unknown as IUSDCAdapter;
  }
}
