/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMedianInterface extends Interface {
  getFunction(
    nameOrSignature: "priceHistory" | "read" | "update"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "read", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
}

export interface IMedian extends BaseContract {
  connect(runner?: ContractRunner | null): IMedian;
  waitForDeployment(): Promise<this>;

  interface: IMedianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  priceHistory: TypedContractMethod<
    [index: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  read: TypedContractMethod<[], [[bigint, bigint]], "view">;

  update: TypedContractMethod<
    [
      _prices: BigNumberish[],
      _timestamps: BigNumberish[],
      _signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<[index: BigNumberish], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "read"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "update"
  ): TypedContractMethod<
    [
      _prices: BigNumberish[],
      _timestamps: BigNumberish[],
      _signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
