/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAdapterSol from "./IAdapter.sol";
export type { iAdapterSol };
export type { IFeed } from "./IFeed";
export type { IMedian } from "./IMedian";
export type { IVault } from "./IVault";
export type { IxNGN } from "./IxNGN";
