/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { USDCAdapter__factory } from "./USDCAdapter__factory";
export { XNGNAdapter__factory } from "./XNGNAdapter__factory";
